version: '3.7'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./scripts/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql